<a href="https://colab.research.google.com/github/Gitacnt-Bhargav/Cpp/blob/master/E2EDeepLearningProjectWithSimpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Process
Data Set -> Feature Engineering -> Ingested into Simple RNN to train RNN Model -> model file to be stored in .h5 using keras lib -> Streamlit webapp -> Deployment

We also need to use Embedding Layer, Simple RNN for training neural network

Embedding Layer:

Converting input layer words to Vectors using Word Embedding (eg. Word2Vec)


### Word Embedding [Feature Representation]

Word to Vector.
Word Embedding will be like a layer similar to Dense layer.

Lets say we have data set with input text <x11, x12, x13, x14> with ouput 0
input text <x21, x22, x23, x24> with ouput 1
and so on

If we want to give input to the RNN model, whatever with xit (word wrt timestamp), we need to convert to vector using Embedding layer.

Lets say we are using OHE, where we have vocabulary, if there is any match to one of the input word, then the value in vector corresponding to that word would be 1. This would create a Sparse matrix which would cause Overfitting.

In order to overcome this, we use Word Embedding like Wrord2Vec.

Word2Vec is a Word embedding technique which can be used in the Embedding layer.

eg.
Index                   2000 5000 6000 9000 1000 7000
of word in vocab        Boy Gift King Queen Apple Mango

For all these words we will select feature representation, and each word would be represented in some dimension. For eg, lets take 300 dimension vector, where each word would be represented with 300 features based on their relation of word with feature

Features may include - Gender, Royal, Age, Food,...

<Refer Word2Vec>

Vocab Size |V| - 10000
Feature dimension - 300

    

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences

sent = ['the glass of milk','the glass of juice','the cup of tea','I am a good boy','I am a good developer',
        'understand the meaning of words','your videos are good']



In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocab size

voc_size = 10000

In [5]:
### one hot represenation for every word

one_hot_repr = [one_hot(words, voc_size) for words in sent]


In [6]:
one_hot_repr

[[8101, 4645, 4715, 1932],
 [8101, 4645, 4715, 5372],
 [8101, 4559, 4715, 2226],
 [5736, 8271, 9880, 4360, 5508],
 [5736, 8271, 9880, 4360, 8724],
 [4147, 8101, 5933, 4715, 4596],
 [4867, 6745, 5970, 4360]]

In [7]:
## in above output, "the" is given in 8101 index out of voc_size of 10000 and so on

In word embedding if we take all vectors, and we plot using PCA (Principal component analysis), and we convert this 300 dimensions into two dimension by dimension reduction, and plot all these vectors, vectors near to each other are actually similar.

we can use cosine similarity - being used in Recommendation engine.

As we know, there are some problems with OHE, so we will convert all our words into indexes (as shown in above step - one_hot_repr)

Now we will take all words, sentence by sentence and pass them to embedding layer and will try to convert these into a word embedding representation

In [10]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences #  is used to transform a list of sequences (lists of integers, for example) into a 2D NumPy array.
from tensorflow.keras.models import Sequential

#pad_sequences is mainly to make all sentences into equal size. basically input sentences might have few of 4 words, few of 7 words,
#with pad_sequence we would make them to equal size



In [11]:
import numpy as np


In [15]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
# this will add 0s before or after to words with lesser length to make it to siex of sent_length
print(embedded_docs)

[[   0    0    0    0 8101 4645 4715 1932]
 [   0    0    0    0 8101 4645 4715 5372]
 [   0    0    0    0 8101 4559 4715 2226]
 [   0    0    0 5736 8271 9880 4360 5508]
 [   0    0    0 5736 8271 9880 4360 8724]
 [   0    0    0 4147 8101 5933 4715 4596]
 [   0    0    0    0 4867 6745 5970 4360]]


In [16]:
## feature representations

dim = 10

In [17]:
# embedding layer mdoel

model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step


array([[[ 0.02098708,  0.04890771, -0.01058131, -0.00200962,
          0.03501162, -0.03548448, -0.0191483 , -0.04086775,
         -0.03602751, -0.00077069],
        [ 0.02098708,  0.04890771, -0.01058131, -0.00200962,
          0.03501162, -0.03548448, -0.0191483 , -0.04086775,
         -0.03602751, -0.00077069],
        [ 0.02098708,  0.04890771, -0.01058131, -0.00200962,
          0.03501162, -0.03548448, -0.0191483 , -0.04086775,
         -0.03602751, -0.00077069],
        [ 0.02098708,  0.04890771, -0.01058131, -0.00200962,
          0.03501162, -0.03548448, -0.0191483 , -0.04086775,
         -0.03602751, -0.00077069],
        [-0.01226036,  0.04951444, -0.04142527,  0.04000201,
          0.01172377,  0.02526489, -0.03993507,  0.04552433,
          0.00137471,  0.013245  ],
        [-0.04323689,  0.03217416, -0.01604229,  0.02582783,
          0.02603758,  0.03351071,  0.04199089,  0.03006815,
          0.03424202, -0.02863977],
        [-0.02151508,  0.0047282 , -0.04562365,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 8101, 4645, 4715, 1932], dtype=int32)

In [23]:
model.predict(embedded_docs)[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([ 0.02098708,  0.04890771, -0.01058131, -0.00200962,  0.03501162,
       -0.03548448, -0.0191483 , -0.04086775, -0.03602751, -0.00077069],
      dtype=float32)